media_commentaire:
        resource: "@MediaBundle/Resources/config/routing/commentaire.yml"
        prefix:   /commentaire

media_homepage:
    path:     /default
    defaults: { _controller: MediaBundle:Default:index }

media:
    resource: "@MediaBundle/Resources/config/routing/album.yml"
    prefix:   /


